volumes:
  db_data_prod:
  minio_data_preprod:
  grafana_data_preprod:
  prometheus_data_preprod:

services:
  postgres:
    image: postgres
    container_name: trackntrain_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  minio: 
    image: minio/minio:latest
    container_name: trackntrain_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: coak
      MINIO_ROOT_PASSWORD: 123456789
      MINIO_BROWSER_REDIRECT_URL: https://minio.trackntrain.fr/console/
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_preprod:/data
    restart: unless-stopped

  api:
    image: ghcr.io/track-train/api
    container_name: trackntrain_backend
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - minio
    environment:
      ENV: prod
      SECRET_KEY: 123456789
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      DATABASE_URL: postgresql://user:user@91.169.178.154:5400/postgres
    restart: unless-stopped
  
  frontend:
    image: ghcr.io/track-train/front
    container_name: trackntrain_frontend
    depends_on:
      - api
    ports:
      - '5173:5173'
    volumes:
      - node_modules:/app/node_modules
      - ./src:/app/src
    environment:
      VITE_APP_API_URL: http://localhost:8000
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: trackntrain_watchtower
    command: 
      - --interval
      - "${WATCHTOWER_INTERVAL:-300}"
      - --label-enable
      - --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana:latest
    container_name: trackntrain_grafana
    ports:
      - '4000:4000'
    environment:
      GF_SERVER_HTTP_PORT: 4000
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_ROOT_URL: http://grafana.trackntrain.fr
    volumes:
      - grafana_data_preprod:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: trackntrain_prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data_preprod:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped