# host_vars/like-it.coak.fr.yml
# ------------------------------------------------------------------------------------------------
project_path: trackntrain
environment: prod

db_external_port: 5432
back_external_port: 8000
front_external_port: 3000

back_image: ghcr.io/likes-it/api:prod
front_image: ghcr.io/likes-it-front:prod

db_volume: db_data_prod
db_container: hexapi-db-prod
back_container: hexapi-app-prod
front_container: like-it-front-prod
watchtower_container: watchtower
