---
  - name: Création du répertoire de déploiement
    ansible.builtin.file:
      path: "{{ project_root }}/{{ inventory_hostname }}"
      state: directory
      owner: user
      group: user
      mode: '0755'

  - name: Génération de docker-compose.yml
    ansible.builtin.template:
      src: docker-compose.j2
      dest: "{{ project_root }}/{{ inventory_hostname }}/docker-compose.yml"
      mode: '0644'

  - name: Génération du fichier .env
    ansible.builtin.template:
      src: env.j2
      dest: "{{ project_root }}/{{ inventory_hostname }}/.env"
      mode: '0644'

  # - name: Génération du fichier prometheus.yml
  #   ansible.builtin.template:
  #     src: prometheus.yml.j2
  #     dest: "{{ project_root }}/{{ inventory_hostname }}/prometheus.yml"
  #     mode: '0644'
  
  - name: Vérifier si des services Docker Compose tournent
    command:
      cmd: docker compose -f "{{ project_root }}/{{ inventory_hostname }}/docker-compose.yml" ps -q
    register: compose_ps
    changed_when: false
    failed_when: false

  - name: Arrêt des services existants (Compose CLI)
    shell: docker compose down
    args:
      chdir: "{{ project_root }}/{{ inventory_hostname }}"
    when: compose_ps.stdout_lines | length > 0

  - name: Démarrage et construction des services (Compose CLI)
    shell: docker compose up --build -d
    args:
      chdir: "{{ project_root }}/{{ inventory_hostname }}"
    when: not ansible_check_mode
