name: 🚀 Ansible Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment target'
        required: true
        default: 'pre_prod'
        type: choice
        options:
          - pre_prod
          - prod
      dry_run:
        description: 'Check mode (dry-run)'
        required: false
        default: false
        type: boolean

env:
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'prod' && 'production' || 'staging' }}

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install Ansible
        run: pip install ansible

      - name: 🔑 Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy to ${{ inputs.environment == 'prod' && 'PRODUCTION' || 'PRE-PRODUCTION' }}
        working-directory: ansible
        run: |
          echo '${{ inputs.environment == 'prod' && secrets.VAULT_PASSWORD_PROD || secrets.VAULT_PASSWORD_PRE_PROD }}' > vault_pass.txt
          ansible-playbook -i hosts playbooks/site.yml \
            --limit=${{ inputs.environment }} \
            --vault-password-file vault_pass.txt \
            ${{ inputs.dry_run == true && '--check' || '' }}
          rm vault_pass.txt